/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnswerGrid: typeof import('./src/components/AnswerGrid.vue')['default']
    AvatarPic: typeof import('./src/components/AvatarPic.vue')['default']
    ConfirmDialog: typeof import('./src/components/ConfirmDialog.vue')['default']
    DrainRing: typeof import('./src/components/DrainRing.vue')['default']
    HostAvatar: typeof import('./src/components/HostAvatar.vue')['default']
    HostAvatarPicker: typeof import('./src/components/HostAvatarPicker.vue')['default']
    HostBar: typeof import('./src/components/HostBar.vue')['default']
    LucideChevronLeft: typeof import('~icons/lucide/chevron-left')['default']
    LucideChevronRight: typeof import('~icons/lucide/chevron-right')['default']
    LucideEye: typeof import('~icons/lucide/eye')['default']
    LucideEyeOff: typeof import('~icons/lucide/eye-off')['default']
    LucideLogOut: typeof import('~icons/lucide/log-out')['default']
    LucidePencil: typeof import('~icons/lucide/pencil')['default']
    LucidePlus: typeof import('~icons/lucide/plus')['default']
    LucideUser: typeof import('~icons/lucide/user')['default']
    PasswordInput: typeof import('./src/components/PasswordInput.vue')['default']
    QuizPreview: typeof import('./src/components/QuizPreview.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeButton: typeof import('./src/components/ThemeButton.vue')['default']
  }
}
