/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnimatedQr: typeof import('./src/components/AnimatedQr.vue')['default']
    AnswerGrid: typeof import('./src/components/AnswerGrid.vue')['default']
    AvatarPic: typeof import('./src/components/AvatarPic.vue')['default']
    CodeStep: typeof import('./src/components/CodeStep.vue')['default']
    ConfirmDialog: typeof import('./src/components/ConfirmDialog.vue')['default']
    DrainRing: typeof import('./src/components/DrainRing.vue')['default']
    HostAvatar: typeof import('./src/components/HostAvatar.vue')['default']
    HostAvatarPicker: typeof import('./src/components/HostAvatarPicker.vue')['default']
    HostBar: typeof import('./src/components/HostBar.vue')['default']
    ImageField: typeof import('./src/components/ImageField.vue')['default']
    LucideCheck: typeof import('~icons/lucide/check')['default']
    LucideChevronLeft: typeof import('~icons/lucide/chevron-left')['default']
    LucideChevronRight: typeof import('~icons/lucide/chevron-right')['default']
    LucideCopy: typeof import('~icons/lucide/copy')['default']
    LucideEye: typeof import('~icons/lucide/eye')['default']
    LucideEyeOff: typeof import('~icons/lucide/eye-off')['default']
    LucideImagePlus: typeof import('~icons/lucide/image-plus')['default']
    LucideImageUp: typeof import('~icons/lucide/image-up')['default']
    LucideLogOut: typeof import('~icons/lucide/log-out')['default']
    LucidePencil: typeof import('~icons/lucide/pencil')['default']
    LucidePlay: typeof import('~icons/lucide/play')['default']
    LucidePlus: typeof import('~icons/lucide/plus')['default']
    LucideSettings: typeof import('~icons/lucide/settings')['default']
    LucideTrash2: typeof import('~icons/lucide/trash2')['default']
    LucideUser: typeof import('~icons/lucide/user')['default']
    PasswordInput: typeof import('./src/components/PasswordInput.vue')['default']
    QuestionRail: typeof import('./src/components/QuestionRail.vue')['default']
    QuestionSettings: typeof import('./src/components/QuestionSettings.vue')['default']
    QuestionSlide: typeof import('./src/components/QuestionSlide.vue')['default']
    QuizLibrary: typeof import('./src/components/QuizLibrary.vue')['default']
    QuizPreview: typeof import('./src/components/QuizPreview.vue')['default']
    QuizSettingsDialog: typeof import('./src/components/QuizSettingsDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeButton: typeof import('./src/components/ThemeButton.vue')['default']
  }
}
